language: python
python:
    - 3.7
notifications:
    slack: astrochats:tV2KNwL9jXSGSv5KhulGNVro
git:
    depth: 3

# Setup anaconda
before_install:
# Install packages
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda;
install:
    - conda update setuptools
    - conda config --add channels conda-forge
    - conda install --yes python=$TRAVIS_PYTHON_VERSION astrocats astropy corner coveralls cython dropbox emcee extinction inflect jupyter matplotlib mpi4py nbstripout numexpr palettable schwimmbad scipy!=0.19.0 seaborn six
    - pip install googletrans
    - coverage run -p setup.py install

# Run test
script:
    - ./test.sh -c

# Run coveralls
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then coveralls; fi
